### ISSUE TITLE
Paketname

### ISSUE THREAD

**Issue by L3P3** [LFF5644/mc-testplugin#1]
Da steht package = one.lff, aber das ist nur deine Domain, das Paket muss also etwa das sein: one.lff.mc-testplugin

**Comment by LFF5644** [comment]
ne one.lff.testplugin mc- istnur für github genau wie site-

**Comment by LFF5644** [comment]
ja aber die sind ja nicht im gleichen ordner die sind dann ganz wo anders

**Comment by LFF5644** [comment]
das project ist unter `/home/lff/bind/myOwnProgrammes/java/testplugin/src/main/java/one/lff/Plugin.java` mein java projecte verzeichnis ist also in `/home/lff/bind/myOwnProgrammes/java/` und da befindet sich das `testplugin` und `HelloWorld` und da kommen die projecte rein also ist egal wo das ist ja nur fürs project seleber ich weiss nicht ob du das versteht xD xD

**Comment by LFF5644** [comment]
gut ändere ich wenns probeleme gibt !

**Comment by L3P3** [comment]
Problem gefunden: Siehe oben
